/**
 * Movie-Net-Backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PieceType = 'Pawn' | 'Rook' | 'Bishop' | 'Knight' | 'Queen' | 'King';

export const PieceType = {
    Pawn: 'Pawn' as PieceType,
    Rook: 'Rook' as PieceType,
    Bishop: 'Bishop' as PieceType,
    Knight: 'Knight' as PieceType,
    Queen: 'Queen' as PieceType,
    King: 'King' as PieceType
};